# [logging]
# level="error"

[general]
pidfile="burrow.pid"

[zookeeper]
servers=[ "localhost:2181" ]
timeout=6
root-path="/burrow"

[evaluator.mystorage]
class-name="caching"
minimum-complete=1.0

[cluster.test]
class-name="kafka"
servers=[ "localhost:9092" ]

[consumer.consumer-group-id]
class-name="kafka"
cluster="test"
servers=[ "localhost:9092" ]
# offsets-topic="topic-A"

[httpserver.default]
address=":8000"
timeout=300

[storage.default]
class-name="inmemory"
workers=20
intervals=30
# We only monitor consumer groups which have committed offsets in the last 24 hours.
expire-group=86400
# Store just one value for every 60 seconds, this coupled with intervals=n means our sliding window
# is of n minutes.
min-distance=60
